### PR TITLE
Change who can exec $clear cmd

### PR DESCRIPTION
**Pull request by adiyenuubarii**
I've updated the file so that only the mods can clear messages.

### CODE REVIEW

**Comment by traliotube** [comment]
pls make it so that bot prunes if the person running it has permission to prune, not if only my acc runs cmd

**Comment by adiyenuubarii** [comment]
updated

**Review by traliotube — CHANGES_REQUESTED** [review]
Pls change _**only mods can use this command!**_ to _**Only mods can use this command!**_

**Comment by adiyenuubarii** [comment]
done

**Comment by traliotube** [comment]
Wonderful, Thanks a lot for your free support Adi Yennubarji

**Pull request merged**
